// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJB2A_xMgTjI6KZqErAaJvAHfQmCMmcus',
    appId: '1:902801366802:web:a51f3232d546a8690dddcb',
    messagingSenderId: '902801366802',
    projectId: 'yaku-e6100',
    authDomain: 'yaku-e6100.firebaseapp.com',
    storageBucket: 'yaku-e6100.appspot.com',
    measurementId: 'G-MQNQKJF4QV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTdzo3vPehBF0rrscU7_3z1dINq8Mqh_c',
    appId: '1:902801366802:android:39a3a8b0dea48a540dddcb',
    messagingSenderId: '902801366802',
    projectId: 'yaku-e6100',
    storageBucket: 'yaku-e6100.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYpE_1CdEa6VmM_G8K0QeD6AsS8oAHAjo',
    appId: '1:902801366802:ios:5e3fe334b613db3d0dddcb',
    messagingSenderId: '902801366802',
    projectId: 'yaku-e6100',
    storageBucket: 'yaku-e6100.appspot.com',
    iosBundleId: 'com.example.yakuUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYpE_1CdEa6VmM_G8K0QeD6AsS8oAHAjo',
    appId: '1:902801366802:ios:248c2122187e9fae0dddcb',
    messagingSenderId: '902801366802',
    projectId: 'yaku-e6100',
    storageBucket: 'yaku-e6100.appspot.com',
    iosBundleId: 'com.example.yakuUser.RunnerTests',
  );
}
